# Generated by Django 4.2.8 on 2023-12-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_service_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="personnel",
            name="facebook",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personnel",
            name="linkedin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="personnel",
            name="slug",
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personnel",
            name="twitter",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
