# Generated by Django 4.2.8 on 2023-12-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_personnel_facebook_personnel_linkedin_personnel_slug_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
