# Generated by Django 4.1.4 on 2024-01-04 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_project_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='partenaire',
            name='site',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='partenaire',
            name='slug',
            field=models.SlugField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='brefDescription',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
