# Generated by Django 4.1.4 on 2024-01-04 19:06

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_partenaire_site_partenaire_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='intitule',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='resume',
            field=models.CharField(max_length=550, verbose_name="Bref Resumé de l'actualité à afficher avant les détails:"),
        ),
        migrations.AlterField(
            model_name='service',
            name='brefDescription',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='description à affiche avant les détail'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='Description detaillé du service'),
        ),
    ]
