# Generated by Django 4.1.4 on 2024-01-04 19:11

from django.db import migrations, models
import datetime
date_time = datetime.datetime.now()




class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_actualite_intitule_alter_actualite_resume_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='date_ofActuality',
            field=models.DateField(default=date_time.strftime("%Y-%m-%d")),
            preserve_default=False,
        ),
    ]
